### PR TITLE
Bug 1480165 - key rotation for gecko-3-b-win2012

### PR DESCRIPTION
**Pull request by grenade**

### CODE REVIEW

**Comment by grenade** [comment]
it looks like the check above is failing because of the existing key rather than the one being added.

/work/repo/generic-worker/2018-05-25_2018-09-25_gecko-3-b-win2012/gecko-3-b-win2012.pub
Earliest expiry is 2018-09-25T00:00:00+00:00 .
ERROR: /work/repo/generic-worker/2018-05-25_2018-09-25_gecko-3-b-win2012/gecko-3-b-win2012.pub expires within 30 days: 2018-09-25T00:00:00+00:00!

**Comment by grenade** [comment]
it looks like the check below is failing because of the existing key rather than the one being added.

/work/repo/generic-worker/2018-05-25_2018-09-25_gecko-3-b-win2012/gecko-3-b-win2012.pub
Earliest expiry is 2018-09-25T00:00:00+00:00 .
ERROR: /work/repo/generic-worker/2018-05-25_2018-09-25_gecko-3-b-win2012/gecko-3-b-win2012.pub expires within 30 days: 2018-09-25T00:00:00+00:00!

**Review by escapewindow — APPROVED** [review]

**Comment by escapewindow** [comment]
Thanks!

**Comment by escapewindow** [comment]
Tagged. This should roll out within an hour or so. Once we've cut over to the new key, I'll wait a few days and then remove the old key.

**Pull request merged**
