### PR TITLE
bug 1470496 - remove all per-instance scriptworker keys

### PR DESCRIPTION
**Pull request by escapewindow**
In bug 1470496, we added a single shared cot gpg key for all prod
scriptworker instances. Now that nearly a month has passed, we can
remove all the old keys.

@MihaiTabara @JohanLorenzo @tomprince we don't have any production scriptworkers pinned to an ancient non-production puppet env, correct?

### CODE REVIEW

**Comment by escapewindow** [comment]
That's my key that's expiring =\

**Comment by escapewindow** [comment]
This will fail until https://github.com/mozilla-releng/build-puppet/pull/133 lands.

**Comment by JohanLorenzo** [comment]
Okay to remove all these keys! For anybody wondering, the unique key was added in https://github.com/mozilla-releng/cot-gpg-keys/pull/50.

Just to make sure: if we needed to rotate the unique key, anybody who has its key `trusted` can generate and sign a new one, right?

**Review by JohanLorenzo — APPROVED** [review]

**Review by MihaiTabara — APPROVED** [review]
This looks good to me, too. +1 to what @JohanLorenzo asked about potentially rotating the single key.

**Comment by escapewindow** [comment]
> Just to make sure: if we needed to rotate the unique key, anybody who has its key trusted can generate and sign a new one, right?

Correct :) Then they'd put the new key here and in hiera.

**Comment by escapewindow** [comment]
The rerun is green: https://tools.taskcluster.net/groups/PMVjn7DWSMSi7csDkJX6DQ/tasks/PMVjn7DWSMSi7csDkJX6DQ/runs/1

**Pull request merged**
